apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: mydsspec
 selector: matchLabels
  type: webserver
 template:
  metadata:   
   name: mypod
   labels:    
    type: webserver
spec:
 containers:
 - image: nginx
   name: c1