apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from Kubernetes Job"]
      restartPolicy: Never

#kubectl apply -f job.yaml
#kubectl get jobs
#kubectl get pods
#kubectl logs <podName>

# A Kubernetes Job is used to run a one-time task.