---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:2
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
          initialDelaySeconds: 15   # Wait 5 seconds before first probe
          periodSeconds: 60       # Check every 5 seconds
          timeoutSeconds: 5        # Timeout after 3 seconds
        livenessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 15  # Wait 15 seconds before first probe
          periodSeconds: 60       # Check every 10 seconds
          timeoutSeconds: 5       # Timeout after 5 seconds
...

---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 80
         
         
# kybectl apply -f <filename.yaml>
# kubectl get pods
# kubectl get svc
# kubectl get endpoints rp
# kubectl describe svc rp        