---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-lbl
spec:
  containers:
    - name: nginx-con
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: naginx-svc
spec:
  type: LoadBalancer
  selector:
    name: nginx-lbl
  ports:
    - port: 80
      targetPort: 80
---

# kubectl apply -f test-pod-service.yaml
# kubectl get svc
# kubctl describe svc nginx-svc
# kubctl edit pod nginx-pod


