---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80

...


---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc2
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

...

# kubectl apply -f test-replication-controller.yaml
# kubectl get rc  (get replication controller)
# kubectl get pods
# kubectl descibe svc <Service Name>
# kubectl descibe svc myapp-svc2 (It will display all end points)